Update `.tool-versions` support
This commit updates the version of Node to the current LTS. The setup
script has also been updated for environments that have `asdf`.

This commit also updates `package.json` with the version that got
generated when running the setup script.

Ref:
- https://asdf-vm.com/
- https://nodejs.org/en/download/releases

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -1,5 +1,14 @@
 #!/usr/bin/env sh
 
+# Exit if any subcommand fails
 set -e
 
-npm install
+if [ -z "$CI" ]; then
+  if command -v asdf > /dev/null; then
+    asdf plugin add nodejs || true
+    asdf plugin update --all || true
+    asdf install
+  fi
+
+  npm install
+fi
